### ISSUE TITLE
UNREGISTERED_PLATFORM

### ISSUE THREAD

**Issue by bhavintce** [doldsimo/lti-1.3-canvas-lms#1]
![image](https://github.com/doldsimo/lti-1.3-canvas-lms/assets/123927710/b05c6c22-22d3-4123-a814-e71567f3d4d9)

{"status":400,"error":"Bad Request","details":{"message":"UNREGISTERED_PLATFORM"}}

**Comment by doldsimo** [comment]
Hi @bhavintce,

thanks for the issue, it's very difficult for me to say exactly what the problem could be with this less information. Would you like to describe your problem in more detail, when and where exactly does the error happen?

Since my example application uses lti.js under the hood, the following issue from lit.js could solve you issue.
Here was an error similar to what it looks like `{"status":400,"error":"Bad Request","details":{"message":"UNREGISTERED_PLATFORM"}}` [more informations](https://github.com/Cvmcosta/ltijs/issues/87#issuecomment-794629510)

So maybe your issue is in the registerPlatform method.
What URLs are you using for it? Specifically the `url` and `clientId`.

So please check your configufiguration. 

Let me know if it solves your issue.

**Comment by bhavintce** [comment]
@doldsimo I have set up "canvas-lms" in the local machine and project URL is "http://canvas.docker". 

Process steps.
-Go to admin and create LTI Key App (screenshot attached below)
-Changed dynamic_settings.yml file as per readme.md file development to production.
-Then this app developer clientId and  LTI_KEY set in server projects.
-Server index.js changed code.
```
let abc =   await lti.registerPlatform({
    url: 'http://canvas.docker', 
    name: 'canvas.docker',
    clientId: '10000000000007',
    authenticationEndpoint: 'http://canvas.docker/api/lti/authorize_redirect',
    accesstokenEndpoint: 'http://canvas.docker/login/oauth2/token',
    authConfig: { method: 'JWK_SET', key: 'https://oauth2server.imsglobal.org/jwks' }
  })
```
* When I try http://canvas.docker/jwks and hit this URL it's getting blank. so I used  https://oauth2server.imsglobal.org/jwks it is correct?

![image](https://github.com/doldsimo/lti-1.3-canvas-lms/assets/123927710/4fabfa59-3abd-4f19-b4dc-f639116a81db)
![image](https://github.com/doldsimo/lti-1.3-canvas-lms/assets/123927710/2e948fce-1f44-4cd7-ac5c-c4c1b6ebef15)


getting blank object when printing abc variable

**Comment by doldsimo** [comment]
@bhavintce thanks for the detailed information.

You also did [step 4](https://github.com/doldsimo/lti-1.3-canvas-lms#4-install-lti-app-inside-canvas) from the readme.md, i.e. registered the plugin? and the clientID matches the one in your index.js?

In my canvas instance, the key was at the following URL: 
``https://canvas.exampledomain.com/api/lti/security/jwks``
so please try out: 
``
    authConfig: { method: 'JWK_SET', key: 'https://canvas.exampledomain.com/api/lti/security/jwks` }
``
You have to use the key from your instance there.

Maybe two more comments, if you set up the Canvas instance locally with the Canvas [Quick Start](https://github.com/instructure/canvas-lms/wiki/Quick-Start), this could cause problems with the LTI plugin. In my scenario, I used an instance that was accessible on the web via HTTPS and was set up with [Production Start](https://github.com/instructure/canvas-lms/wiki/Production-Start).

**Comment by bhavintce** [comment]
Hi @doldsimo 

Yes I checked step 4 register plugin client same as index.js. Also, canvas production was set and deployed on AWS bitnami instance, and  changed development: to production: inside the dynamic_settings.yml file and restart apache2

My canvas project JWKS getting blank: https://ec2-100-26-251-126.compute-1.amazonaws.com/api/lti/security/jwks
So I am using  https://oauth2server.imsglobal.org/jwks it's correct?

Can you please guide me more what is issue?

Index.js
```
const plat = await lti.registerPlatform({
      url: 'http://ec2-100-26-251-126.compute-1.amazonaws.com',
      name: 'Eflok-2-Aug',
      clientId: '10000000000002',
      authenticationEndpoint:'http://ec2-100-26-251-126.compute-1.amazonaws.com/api/lti/authorize_redirect',
      accesstokenEndpoint:'http://ec2-100-26-251-126.compute-1.amazonaws.com/login/oauth2/token',
      authConfig: { 
        method: 'JWK_SET', 
        key: 'https://oauth2server.imsglobal.org/jwks'} //'https://canvas.instructure.com/api/lti/security/jwks'
    })
    console.log("plat=====>>>>",plat);
    
    plat variable getting the blank object
```
.env
```
LTI_KEY = Set LTI key generated then click show key add this LTI_KEY variable
```

https://tinyurl.com/29pbng6g

**Comment by doldsimo** [comment]
Hi @bhavintce,

in general I think the error is just because some configuration issue with the Canvas platform and the LTI plugin. The rest of it should work fine.

When I open your JWKS URL I can see some keys.
You should use https://ec2-100-26-251-126.compute-1.amazonaws.com/api/lti/security/jwks insted of https://oauth2server.imsglobal.org/jwks. (but maybe SSL could lead to issues because it is accessable via http)

Also try the following:
your `url`: should be the same as in the ISS value in the config/security.yml file, so it depends on the config form the Canvas Instance. So for example when the iss value is  `https://canvas.instructure.com` inside the  config/security.yml file, set the `url` to this value.

Maybe you can also try to add an SSL certificate to the Canvas Instance but I think the LTI plugin sould also work fine without a SSL on the LMS site. 

Inside your .env you should define more values. So that ones you are using in the index.js.

**Comment by bhavintce** [comment]
It's working fine. now.  Thanks, @doldsimo issue is URL miss match.
